server:
  port: 8100

# 路由转发，将/member/*的请求转发到/member模块
spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: member
              uri: lb://member
              predicates:
                - Path=/member/**
            - id: business
              uri: lb://business
              predicates:
                - Path=/business/**
            - id: batch
              uri: lb://batch
              predicates:
                - Path=/batch/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns: "*"
                allowed-headers: "*"
                allowed-methods: "*"
                allow-credentials: true
                max-age: 3600
    nacos:
      # 注册与发现中心
      discovery:
        server-addr: localhost:8848
        namespace: 1a7dda0c-1ac0-4f74-979a-6bc32f2bfcc3
        service: gateway
        heartbeat-interval: 5
        weight: 1