server:
  port: 8100

# 路由转发，将/member/*的请求转发到/member模块
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: member
              uri: http://127.0.0.1:8101
              predicates:
                - Path=/member/**
            - id: business
              uri: http://127.0.0.1:8102
              predicates:
                - Path=/business/**
            - id: batch
              uri: http://127.0.0.1:8102
              predicates:
                - Path=/batch/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns: "*"
                allowed-headers: "*"
                allowed-methods: "*"
                allow-credentials: true
                max-age: 3600
