server:
  port: 8103
  servlet:
    context-path: /batch # 方便路由转发

spring:
  application:
    name: batch
  profiles:
    active: dev
  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/train?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 741963
  cloud:
    nacos:
      # 配置中心
      config:
        server-addr: 127.0.0.1:8900
        namespace: 1a7dda0c-1ac0-4f74-979a-6bc32f2bfcc3
        file-extension: yml
        group: DEFAULT_GROUP
        refresh-enabled: true  # 配置变更自动刷新
      # 注册与发现中心
      discovery:
        server-addr: 127.0.0.1:8900
        namespace: 1a7dda0c-1ac0-4f74-979a-6bc32f2bfcc3
        service: batch
        heartbeat-interval: 5
        weight: 1

#mybatis xml路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.yali.member.mapper: TRACE
## seata 事务组名称
#seata:
#  tx-service-group: train-group
#  service:
#    vgroup-mapping:
#      train-group: default
#    grouplist:
#      default: localhost:8091